import { useState } from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import { cookies } from 'next/dist/client/components/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const getThemeFromCookie = () => {
  const themeToken = cookies().get('theme');

  if (themeToken && (themeToken.value === 'light' || themeToken.value === 'dark')) {
    return themeToken.value;
  }
  return 'light';
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const [theme, setTheme] = useState<'light' | 'dark'>(getThemeFromCookie());

  const theme = getThemeFromCookie();
  return (
    <html lang="en">
      <body className={`${inter.className} ${theme}`}>{children}</body>
    </html>
  );
}
